MDN/webalyzer/webalyzer/analyzer/urls.py
from django.conf.urls import patterns, url

from webalyzer.analyzer import views


urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^submit/$', views.submit, name='submit'),
    url(
        r'^recent-submissions$',
        views.recent_submissions,
        name='recent_submissions'
    ),
    url(r'^(?P<domain>[\w\.]+)$', views.index, name='analyzed'),
    url(r'^(?P<domain>[\w\.]+)/data$', views.analyzed, name='analyzed_data'),
    url(
        r'^(?P<domain>[\w\.]+)/source/(?P<id>\d+)/$',
        views.index,
        name='source_view'
    ),
    url(
        r'^(?P<domain>[\w\.]+)/source/(?P<id>\d+)/data$',
        views.source_view,
        name='source_view_data'
    ),
    url(
        r'^(?P<domain>[\w\.]+)/download/(?P<id>\d+)/'
        '(?P<which>before|after)/(?P<filename>.*?\.css)$',
        views.download,
        name='download'
    ),
    # url(r'^$', views.analyze, name='analyze'),
    # url(r'^start/$', views.start, name='start'),
    # url(
    #     r'^(?P<domain>[\w\.]+)/source/(?P<id>\d+)/$',
    #     views.source_view,
    #     name='source_view'
    # ),
    # url(
    #     r'^(?P<domain>[\w\.]+)/diff/(?P<id>\d+)/$',
    #     views.diff_view,
    #     name='diff_view'
    # ),
    # url(r'^(?P<domain>[\w\.]+)$', views.analyzed, name='analyzed'),

)

MDN/webalyzer/webalyzer/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns(
    '',
    url(
        r'collector/',
        include('webalyzer.collector.urls', namespace='collector')
    ),
    url(
        r'collected/',
        include('webalyzer.collected.urls', namespace='collected')
    ),
    url(
        r'analyzer/',
        include('webalyzer.analyzer.urls', namespace='analyzer')
    ),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


import djcelery
djcelery.setup_loader()

MDN/webalyzer/webalyzer/analyzer/models.py
from django.db import models


class Result(models.Model):
    domain = models.CharField(max_length=100, db_index=True)
    url = models.URLField()
    line = models.PositiveIntegerField(null=True)  # link's don't have this
    before = models.TextField()
    after = models.TextField()
    ignored = models.BooleanField(default=False)
    modified = models.DateTimeField(auto_now=True)

    @property
    def suspects(self):
        return Suspect.objects.filter(result=self)


class Suspect(models.Model):
    result = models.ForeignKey(Result)
    selector = models.TextField()
    # useful when the selector appears in a bundle with other selectors
    selector_full = models.TextField()
    style = models.TextField()
    line = models.PositiveIntegerField(null=True)  # null if it goes wrong
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('modified',)

    @property
    def size(self):
        return len(self.style)

MDN/webalyzer/webalyzer/analyzer/views.py
import os
import json
import difflib
import hashlib
import tempfile
import subprocess
import shutil
from contextlib import contextmanager

from pygments import highlight
from pygments.lexers import CssLexer, DiffLexer
from pygments.formatters import HtmlFormatter
from jsonview.decorators import json_view

from django import http
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Max
from django.db import transaction
from django.core.cache import cache

from webalyzer.collector.models import Page
from webalyzer.analyzer.models import Result
from .tasks import start_analysis
# from webalyzer.base.helpers import diff_table


def diff_table(before, after):
    diff = difflib.unified_diff(
        before.splitlines(),
        after.splitlines(),
        lineterm='',
        fromfile='original', tofile='optimized'
    )
    return '\n'.join(diff)


@contextmanager
def tmpfilename(content, extension=''):
    filename = hashlib.md5(content.encode('utf-8')).hexdigest()
    if extension:
        filename += '.%s' % (extension,)
    dir_ = tempfile.mkdtemp()
    filepath = os.path.join(dir_, filename)
    with open(filepath, 'w') as f:
        f.write(content)
    try:
        yield filepath
    finally:
        shutil.rmtree(dir_)


def prettify_css(css):
    with tmpfilename(css, 'css') as filename:
        process = subprocess.Popen(
            ['crass', filename, '--pretty'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )
        stdout, stderr = process.communicate()
        if not stdout and stderr:
            raise Exception(stderr)  # ???
        return stdout


def index(request, *args, **kwargs):
    # the *args, **kwargs is because this view is used in urls.py
    # as a catch-all for the sake of pushstate
    context = {}
    html_formatter = HtmlFormatter(linenos=True)
    context['pygments_css'] = html_formatter.get_style_defs('.highlight')
    return render(request, 'analyzer/index.html', context)


@json_view
def recent_submissions(request):
    context = {}
    results = (
        Result.objects.values('domain')
        .annotate(m=Max('modified'))
        .order_by('-m')
    )
    context['domains'] = [x['domain'] for x in results]
    return context


@json_view
@transaction.atomic
def submit(request):
    if request.method != 'POST':  # required_P
        return redirect(reverse('analyzer:start'))

    POST = json.loads(request.body)
    domain = POST['domain']
    start_analysis.delay(domain)
    jobs_ahead = cache.get('jobs_ahead', 0)
    return {
        'jobs_ahead': jobs_ahead,
    }


@json_view
def analyzed(request, domain):
    # from time import sleep
    # sleep(3)
    results = Result.objects.filter(domain=domain)
    if not results.count():
        return {'count': 0}

    pages = Page.objects.filter(domain=domain)
    context = {}
    summed_results = results.extra(
        select={
            'sum_before': 'sum(LENGTH(before))',
            'sum_after': 'SUM(LENGTH(after))',
        }
    )
    # summed_results = summed_results.order_by(False)
    summed = summed_results.values('sum_before', 'sum_after')[0]
    context['total_before'] = summed['sum_before']
    context['total_after'] = summed['sum_after']
    # context['total_potential_saving'] = (context['total_before'] -
    # context['total_potential_saving'] = (
    #     results.aggregate(
    #         Sum('potential_saving')
    #     )['potential_saving__sum']
    # )
    all_results = []
    for result in results.order_by('modified'):
        suspects = []
        for suspect in result.suspects:
            suspects.append({
                'selector': suspect.selector,
                'selector_full': suspect.selector_full,
                'style': suspect.style,
                'line': suspect.line,
                'size': suspect.size,
            })
        if result.url.endswith('min.css'):
            prettified = True
            diff = diff_table(
                prettify_css(result.before),
                prettify_css(result.after)
            )
        else:
            prettified = False
            diff = diff_table(result.before, result.after)
        filename = None
        if not result.line:
            filename = os.path.basename(result.url)
        all_results.append({
            'id': result.id,
            'url': result.url,
            'line': result.line,
            'size_before': len(result.before),
            'size_after': len(result.after),
            # 'before': result.before,
            # 'after': result.after,
            # 'diff': result.unified_diff,
            'unified_diff': diff,
            'ignored': result.ignored,
            'modified': result.modified,
            'suspects': suspects,
            'prettified': prettified,
            'filename': filename,
        })

    context['domain'] = domain
    context['results'] = all_results
    context['pages_count'] = pages.count()
    return context


@json_view
def source_view(request, domain, id):
    result = get_object_or_404(Result, id=id)
    assert result.domain == domain, result.domain
    context = {}

    html_formatter = HtmlFormatter(
        linenos=True,
        lineanchors='L',
        linespans='L',
        anchorlinenos=True
    )
    context['code'] = highlight(
        result.before,
        CssLexer(),
        html_formatter
    )
    context['domain'] = domain
    context['result'] = {
        'id': result.id,
        'url': result.url,
    }
    return context


def diff_view(request, domain, id):
    result = get_object_or_404(Result, id=id, domain=domain)
    context = {}

    html_formatter = HtmlFormatter(
        linenos=True,
        lineanchors='L',
        linespans='L',
        anchorlinenos=True
    )
    context['code'] = highlight(
        diff_table(result.before, result.after),
        DiffLexer(),
        html_formatter
    )
    context['domain'] = domain
    context['result'] = result
    context['pygments_css'] = html_formatter.get_style_defs('.highlight')
    return render(request, 'analyzer/diff_view.html', context)


def download(request, domain, id, which, filename):
    result = get_object_or_404(Result, id=id, domain=domain)
    assert filename.lower().endswith('.css'), filename

    if which == 'before':
        content = result.before
    elif which == 'after':
        content = result.after
    else:
        raise NotImplementedError(which)

    if 'pretty' in request.GET:
        content = prettify_css(content)

    response = http.HttpResponse(
        content,
        content_type='text/css; charset=utf-8'
    )
    response['Content-Disposition'] = 'inline; filename=%s' % (filename,)
    return response

MDN/webalyzer/webalyzer/analyzer/templates/analyzer/partials/analyzed.html
{% verbatim %}
  <h1>Analysis for <code>{{ domain }}</code></h1>


  <div ng-if="!results.length" class="loading" role="alert" ng-cloak>
    <h3>Loading results</h3>
    <div class="loader">
      <div class="loader-inner ball-scale-multiple"><div></div><div></div><div></div></div></div>
  </div>

  <div ng-if="results.length" ng-cloak>
    <h3>Number of collected pages: <b>{{ pages_count }}</b></h3>
    <h3 title="Was: {{ total_before | filesize }}, Could be {{ total_after | filesize }}">
      Potential Total Save:
      <b>{{ (total_before - total_after) | filesize }}</b></h3>


    <h2>Results</h2>
    <div class="result" ng-repeat="result in results">
      <h5>
        <b ng-if="result.line">Inline CSS</b>
        <b ng-if="!result.line">Linked CSS</b>
        <a href="{{ result.url }}">{{ result.url }}</a>
      </h5>
      <p>
        Size before <b>{{ result.size_before | filesize }}</b>
        Size after <b>{{ result.size_after | filesize }}</b><br>
        <span ng-show="!result.inline">
          <b>Download</b>
          <a target="_self" href="/analyzer/{{ domain }}/download/{{ result.id }}/before/{{ result.filename }}">
            original <small>({{ result.size_before | filesize }})</small></a>
          <a target="_self" href="/analyzer/{{ domain }}/download/{{ result.id }}/before/{{ result.filename }}?pretty"
             ng-show="result.prettified">
            original <small>(prettified)</small></a>

          <a target="_self" href="/analyzer/{{ domain }}/download/{{ result.id }}/after/{{ result.filename }}">
            reduced <small>({{ result.size_after | filesize }})</small></a>
          <a target="_self" href="/analyzer/{{ domain }}/download/{{ result.id }}/after/{{ result.filename }}?pretty"
            ng-show="result.prettified">
            reduced <small>(prettified)</small></a>
        </span>
      </p>
      <button type="button" class="diffs"
        ng-class="{'button-primary': result._show_diff}"
        ng-click="showDiff(result)">
        Diff <small ng-show="result.prettified">(prettified)</small></button>
      <button type="button" class="suspects"
        ng-class="{'button-primary': result._show_suspects}"
        ng-click="showSuspects(result)">Suspects ({{ result.suspects.length }})</button>
      <div class="diff" ng-show="result._show_diff">
        <pre>{{ result.unified_diff }}</pre>
      </div>

      <ul class="suspects" ng-show="result._show_suspects">
        <li class="suspect" ng-repeat="suspect in result.suspects">
          <code>{{ suspect.selector }}</code>
            <a ng-if="suspect.line"
            ui-sref="sourceview({domain: domain, id: result.id})"
            ng-click="setSourceViewLine(suspect.line)"
            title="line">#L-{{ suspect.line }}</a>
          <!-- <small>{{ suspect.size | filesize }}</small> -->
          <!-- <pre style="display:none">{{ suspect.selector_full }}</pre> -->
          <!-- <pre>{{ suspect.style }}</pre> -->
        </li>
      </ul>
    </div>
  </div>
  <hr>

  <form method="post" ng-submit="restartAnalysis()">
    <input name="domain" value="{{ domain }}" type="hidden">
    <input class="button-primary" value="Re-submit for analysis" type="submit">
  </form>
{% endverbatim %}

MDN/webalyzer/webalyzer/analyzer/templates/analyzer/partials/diff_view.html
{% verbatim %}
  <h3>Diff view for <a href="{{ result.url }}">{{ result.url }}</a></h3>
  <h5>
    <a href="/analyzer/{{ domain }}/source/{{ result.id }}">
      Source view for <b>{{ result.url }}</b>
    </a>
  </h5>
  <h5>
    <a href="/analyzer/{{ domain}}">
      Back to analysis for <code>{{ domain }}</code>
    </a>
  </h5>

{{ code }}
{% endverbatim %}

MDN/webalyzer/webalyzer/analyzer/templates/analyzer/partials/source_view.html
{% verbatim %}
  <h1>Analysis for <code>{{ domain }}</code></h1>

  <p ng-if="loading">
    Loading source...
  </p>

  <div ng-if="!loading">
    <h3>Source view for <a href="{{ result.url }}">{{ result.url }}</a></h3>
    <h5>
      <a href="/analyzer/{{ domain }}/diff/{{ result.id }}">
        Diff view for <b>{{ result.url }}</b>
      </a>
    </h5>
    <h5>
      <a href="/analyzer/{{ domain }}">
        Back to analysis for <code>{{ domain }}</code>
      </a>
    </h5>
    <!-- <div ng-bind-html="code"></div> -->
    <div bind-html-unsafe="code"></div>
  </div>
{% endverbatim %}

MDN/webalyzer/webalyzer/analyzer/templates/analyzer/partials/start.html
{% verbatim %}
  <h1>Start analysis</h1>

  <form method="post" ng-submit="startAnalysis()">
    <input class="u-full-width" name="domain" ng-model="domain"
    placeholder="mydomain.example.com" id="id_domain" type="text">
    <button class="button-primary" type="submit">{{ loading_message }}</button>
  </form>

  <h3 ng-if="job_submitted">
    <b>{{ job_submitted }}</b> submitted!<br>
    {{ jobs_ahead }} jobs ahead in the queue.
  </h3>
  <h3 ng-if="job_submitted">
    Your report will be available shortly. <br>
    <a href="/analyzer/{{ domain }}">Report for <b>{{ domain }}</b></a>
  </h3>

  <p>
    If you don't know your domain, you might not have submitted anything.<br>
    See <a href="#">Help page</a>.
  </p>

  <p ng-if="recent_domains">
    Here are some recent submissions:
  </p>

  <ul ng-repeat="domain in recent_domains">
    <li><a ui-sref="analyzed({domain: domain})"><code>{{ domain }}</code></a>
  </ul>

{% endverbatim %}